/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collegeadmissionsystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AK Systems
 */
public class ApplicationPannel extends javax.swing.JFrame {

    /**
     * Creates new form ApplicationPannel
     */
    public ApplicationPannel() {
        initComponents();
        displayDataOnTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "CNIC", "Gender", "Percentage", "ReferedCollege", "Assigned College"
            }
        ));
        jTable.setMinimumSize(new java.awt.Dimension(1500, 800));
        jTable.setPreferredSize(new java.awt.Dimension(6000, 2000));
        jTable.setRowHeight(30);
        jTable.setRowMargin(10);
        jScrollPane2.setViewportView(jTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 1480, 330));

        setSize(new java.awt.Dimension(2009, 936));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void displayDataOnTable() {

    System.out.println("hellooa");
    try {
            // Create the SQL query
            String tableName = "stdInfo";
            String tableName2 = "stdEduInfo";
            String query = "SELECT * FROM " + tableName;
            String query2 = "SELECT * FROM " + tableName2;

            // Create a PreparedStatement object
            DBConnector db= new DBConnector();
            
            // Execute the query and get the result set
            ResultSet rs = db.RunSelect(query);
            ResultSet rs2 = db.RunSelect(query2);
            // Loop through the result set and populate the table
            DefaultTableModel model = (DefaultTableModel) jTable.getModel();
            model.setRowCount(0); // Clear the existing table data

            while (rs.next()&&rs2.next()) {
                // Retrieve the data from the result set
            String studentName = rs.getString("name");
            String cnicNo = rs.getString("CNICNo");
            String AssignedCollege = rs.getString("AssignedCollege");
            String gender = rs.getString("Gender");
//            String rollNumber = rs.getString("RollNumber");
            String percentage = rs2.getString("Percentage");
           String referCollege = rs2.getString("ReferredCollege");
                System.out.println(AssignedCollege);
                System.out.println(percentage);
                System.out.println(referCollege);
                // Add the data to the table model
                model.addRow(new Object[]{studentName, cnicNo,gender,percentage,referCollege,AssignedCollege});
            }

            // Close the result set, prepared statement, and connection
            rs.close();
        } catch (SQLException e) {
            e.getMessage();
        }    
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationPannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
